color0 #181211
color1 #ffb4ab
color2 #ffb4a3
color3 #e7bdb4
color4 #dbc58c
color5 #ffb4a3
color6 #e7bdb4
color7 #ede0dd
color8 #a08c88
color9 #ffb4ab
color10 #ffb4a3
color11 #e7bdb4
color12 #dbc58c
color13 #ffb4a3
color14 #e7bdb4
color15 #ede0dd

cursor                #ede0dd
cursor_text_color     #181211
background            #181211
foreground            #ede0dd
selection_foreground  #d8c2bd
selection_background  #534340
active_border_color   #ffb4a3
inactive_border_color #534340
url_color             #ffb4a3

active_tab_foreground   #5e1606
active_tab_background   #ffb4a3
inactive_tab_foreground #d8c2bd
inactive_tab_background #534340
cursor_trail_color      #d8c2bd
